; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=klausscpu -O1 < %s | FileCheck %s

; Branches: all 10 integer condition codes, if/else, loops.

; Signed less-than: CMPRR + JMPLT
define i64 @slt(i64 %a, i64 %b) {
; CHECK-LABEL: slt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    cmpltr r12, r0, r1
; CHECK-NEXT:    andv r12, 1
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %c = icmp slt i64 %a, %b
  %r = select i1 %c, i64 1, i64 0
  ret i64 %r
}

; Signed greater-than-or-equal: CMPRR + JMPGE
define i64 @sge(i64 %a, i64 %b) {
; CHECK-LABEL: sge:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    cmpger r12, r0, r1
; CHECK-NEXT:    andv r12, 1
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %c = icmp sge i64 %a, %b
  %r = select i1 %c, i64 1, i64 0
  ret i64 %r
}

; Unsigned less-than: CMPRR + JMPULT
define i64 @ult(i64 %a, i64 %b) {
; CHECK-LABEL: ult:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    cmpultr r12, r0, r1
; CHECK-NEXT:    andv r12, 1
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %c = icmp ult i64 %a, %b
  %r = select i1 %c, i64 1, i64 0
  ret i64 %r
}

; Equal: CMPRV with constant 0 + JMPE
define i64 @eq_zero(i64 %a) {
; CHECK-LABEL: eq_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    setr r12, 0
; CHECK-NEXT:    cmpeqr r12, r0, r12
; CHECK-NEXT:    cmprv r12, 0
; CHECK-NEXT:    jmpe .LBB3_1
; CHECK-NEXT:    jmp .LBB3_2
; CHECK-NEXT:  .LBB3_1:
; CHECK-NEXT:    setr r12, 20
; CHECK-NEXT:    jmp .LBB3_3
; CHECK-NEXT:  .LBB3_2:
; CHECK-NEXT:    setr r12, 10
; CHECK-NEXT:  .LBB3_3:
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %c = icmp eq i64 %a, 0
  %r = select i1 %c, i64 10, i64 20
  ret i64 %r
}

; Not-equal: CMPRV + JMPNE
define i64 @ne_const(i64 %a) {
; CHECK-LABEL: ne_const:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    setr r12, 42
; CHECK-NEXT:    cmpner r12, r0, r12
; CHECK-NEXT:    andv r12, 1
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %c = icmp ne i64 %a, 42
  %r = select i1 %c, i64 1, i64 0
  ret i64 %r
}

; if/else converging at a single exit.
define i64 @if_else(i64 %a, i64 %b) {
; CHECK-LABEL: if_else:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    cmprr r0, r1
; CHECK-NEXT:    jmple .LBB5_2
; CHECK-NEXT:  # %bb.1: # %then
; CHECK-NEXT:    incr r0
; CHECK-NEXT:    jmp .LBB5_3
; CHECK-NEXT:  .LBB5_2: # %else
; CHECK-NEXT:    decr r1
; CHECK-NEXT:    copy r0, r1
; CHECK-NEXT:  .LBB5_3: # %exit
; CHECK-NEXT:    copy r12, r0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %c = icmp sgt i64 %a, %b
  br i1 %c, label %then, label %else
then:
  %t = add i64 %a, 1
  br label %exit
else:
  %e = sub i64 %b, 1
  br label %exit
exit:
  %r = phi i64 [ %t, %then ], [ %e, %else ]
  ret i64 %r
}

; Countdown loop: while (n > 0) n--; return n;
define i64 @countdown(i64 %n) {
; CHECK-LABEL: countdown:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    incr r0
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB6_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    decr r0
; CHECK-NEXT:    cmprv r0, 0
; CHECK-NEXT:    jmpgt .LBB6_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    copy r12, r0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
entry:
  br label %loop
loop:
  %i = phi i64 [ %n, %entry ], [ %dec, %loop ]
  %c = icmp sgt i64 %i, 0
  %dec = add i64 %i, -1
  br i1 %c, label %loop, label %exit
exit:
  ret i64 %i
}

; Sum loop: for (i=0; i<n; i++) sum += i;
define i64 @sum_loop(i64 %n) {
; CHECK-LABEL: sum_loop:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    setr r12, 0
; CHECK-NEXT:    copy r14, r12
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB7_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    addr r12, r12, r14
; CHECK-NEXT:    incr r14
; CHECK-NEXT:    cmprr r14, r0
; CHECK-NEXT:    jmplt .LBB7_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
entry:
  br label %loop
loop:
  %i   = phi i64 [ 0, %entry ], [ %i1,   %loop ]
  %sum = phi i64 [ 0, %entry ], [ %sum1, %loop ]
  %sum1 = add i64 %sum, %i
  %i1   = add i64 %i,   1
  %c    = icmp slt i64 %i1, %n
  br i1 %c, label %loop, label %exit
exit:
  ret i64 %sum1
}
