; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=klausscpu -O1 < %s | FileCheck %s

; Calling convention: argument registers R0-R3, return R12, callee-saved R4-R7.

declare i64 @ext(i64, i64, i64, i64)
declare void @ext_void()

; Arguments passed in R0-R3.
define i64 @call_4_args(i64 %a, i64 %b, i64 %c, i64 %d) {
; CHECK-LABEL: call_4_args:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addsp -24
; CHECK-NEXT:    call ext
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %r = call i64 @ext(i64 %a, i64 %b, i64 %c, i64 %d)
  ret i64 %r
}

; 5th argument spills to stack at [SP+32].
declare i64 @ext5(i64, i64, i64, i64, i64)
define i64 @call_5_args(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e) {
; CHECK-LABEL: call_5_args:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addsp -32
; CHECK-NEXT:    ldidx64 r12, r15, 40
; CHECK-NEXT:    getsp r14
; CHECK-NEXT:    stidx64 r12, r14, 24
; CHECK-NEXT:    call ext5
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %r = call i64 @ext5(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e)
  ret i64 %r
}

; Callee-saved registers R4-R7 are preserved across calls.
define i64 @callee_saved_live_across_call(i64 %x) {
; CHECK-LABEL: callee_saved_live_across_call:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addsp -32
; CHECK-NEXT:    stidx64 r4, r15, -8 # 8-byte Folded Spill
; CHECK-NEXT:    copy r4, r0
; CHECK-NEXT:    call ext_void
; CHECK-NEXT:    addi r12, r4, 3
; CHECK-NEXT:    ldidx64 r4, r15, -8 # 8-byte Folded Reload
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %saved = add i64 %x, 1
  call void @ext_void()
  %r = add i64 %saved, 2
  ret i64 %r
}

; Prologue/epilogue: push R15, getsp R15, (addsp), setsp R15, pop R15.
define i64 @leaf(i64 %a, i64 %b) {
; CHECK-LABEL: leaf:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addr r12, r0, r1
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %r = add i64 %a, %b
  ret i64 %r
}

; Return value in R12.
define i64 @return_const() {
; CHECK-LABEL: return_const:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    setr r12, 99
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  ret i64 99
}

; Indirect call through function pointer.
define i64 @indirect_call(ptr %fp, i64 %a) {
; CHECK-LABEL: indirect_call:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addsp -24
; CHECK-NEXT:    copy r12, r0
; CHECK-NEXT:    copy r0, r1
; CHECK-NEXT:    callr r12
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %r = call i64 %fp(i64 %a)
  ret i64 %r
}
