; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=klausscpu -O1 < %s | FileCheck %s

; Frame layout: prologue/epilogue, alloca, passing local address.

declare void @use_ptr(ptr)
declare i64 @fill(ptr, i64)

; Prologue: push r15; getsp r15; addsp -N.  Epilogue: setsp r15; pop r15.
define i64 @with_alloca(i64 %x) {
; CHECK-LABEL: with_alloca:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addsp -8
; CHECK-NEXT:    copy r12, r0
; CHECK-NEXT:    stidx64 r0, r15, -8
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %slot = alloca i64
  store i64 %x, ptr %slot
  %v = load i64, ptr %slot
  ret i64 %v
}

; Pass address of local to callee (tests FrameIndex materialisation via ADDI).
define void @pass_local_addr() {
; CHECK-LABEL: pass_local_addr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addsp -32
; CHECK-NEXT:    addi r0, r15, -8
; CHECK-NEXT:    call use_ptr
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %buf = alloca i64
  call void @use_ptr(ptr %buf)
  ret void
}

; Stack array: 8-element i64 array; indexed store then load.
define i64 @stack_array(i64 %i, i64 %v) {
; CHECK-LABEL: stack_array:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addsp -64
; CHECK-NEXT:    shlv r0, 3
; CHECK-NEXT:    addi r12, r15, -64
; CHECK-NEXT:    addr r14, r12, r0
; CHECK-NEXT:    copy r12, r1
; CHECK-NEXT:    stidx64 r1, r14, 0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %arr = alloca [8 x i64]
  %p   = getelementptr [8 x i64], ptr %arr, i64 0, i64 %i
  store i64 %v, ptr %p
  %q   = getelementptr [8 x i64], ptr %arr, i64 0, i64 %i
  %r   = load i64, ptr %q
  ret i64 %r
}

; Callee-saved spill: value live across a call forces R4-R7 spill.
define i64 @spill_across_call(i64 %a) {
; CHECK-LABEL: spill_across_call:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addsp -32
; CHECK-NEXT:    stidx64 r4, r15, -8 # 8-byte Folded Spill
; CHECK-NEXT:    setr r12, 0
; CHECK-NEXT:    copy r4, r0
; CHECK-NEXT:    copy r0, r12
; CHECK-NEXT:    call use_ptr
; CHECK-NEXT:    addi r12, r4, 3
; CHECK-NEXT:    ldidx64 r4, r15, -8 # 8-byte Folded Reload
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %b = add i64 %a, 1
  call void @use_ptr(ptr null)
  %r = add i64 %b, 2
  ret i64 %r
}

; Multiple allocas — all land in the same frame.
define i64 @multi_alloca(i64 %x, i64 %y) {
; CHECK-LABEL: multi_alloca:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addsp -16
; CHECK-NEXT:    addr r12, r0, r1
; CHECK-NEXT:    stidx64 r0, r15, -8
; CHECK-NEXT:    stidx64 r1, r15, -16
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %sx = alloca i64
  %sy = alloca i64
  store i64 %x, ptr %sx
  store i64 %y, ptr %sy
  %vx = load i64, ptr %sx
  %vy = load i64, ptr %sy
  %r  = add i64 %vx, %vy
  ret i64 %r
}
