; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=klausscpu -O1 < %s | FileCheck %s

; Global address materialisation via SETR + load/store.

@g_i64 = global i64 0
@g_i32 = global i32 0
@g_arr = global [4 x i64] zeroinitializer

declare void @ext()

define i64 @read_global_i64() {
; CHECK-LABEL: read_global_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    setr r12, g_i64
; CHECK-NEXT:    ldidx64 r12, r12, 0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %v = load i64, ptr @g_i64
  ret i64 %v
}

define void @write_global_i64(i64 %v) {
; CHECK-LABEL: write_global_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    setr r12, g_i64
; CHECK-NEXT:    stidx64 r0, r12, 0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  store i64 %v, ptr @g_i64
  ret void
}

define i64 @read_global_i32_zext() {
; CHECK-LABEL: read_global_i32_zext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    setr r12, g_i32
; CHECK-NEXT:    memget32 r12, r12
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %v = load i32, ptr @g_i32
  %r = zext i32 %v to i64
  ret i64 %r
}

; Array element: setr base + offset load.
define i64 @read_array_elem(i64 %i) {
; CHECK-LABEL: read_array_elem:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    shlv r0, 3
; CHECK-NEXT:    setr r12, g_arr
; CHECK-NEXT:    addr r12, r12, r0
; CHECK-NEXT:    ldidx64 r12, r12, 0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %p = getelementptr [4 x i64], ptr @g_arr, i64 0, i64 %i
  %v = load i64, ptr %p
  ret i64 %v
}

; Return the address of a global (SETR only, no load).
define ptr @global_addr() {
; CHECK-LABEL: global_addr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    setr r12, g_i64
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  ret ptr @g_i64
}

; External symbol reference.
define i64 @call_ext_and_use() {
; CHECK-LABEL: call_ext_and_use:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addsp -24
; CHECK-NEXT:    call ext
; CHECK-NEXT:    setr r12, g_i64
; CHECK-NEXT:    ldidx64 r12, r12, 0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  call void @ext()
  %v = load i64, ptr @g_i64
  ret i64 %v
}
