; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --default-march klausscpu
; RUN: llc -march=klausscpu -verify-machineinstrs -O1 < %s | FileCheck %s

; 1-word forms preferred over 2-/3-word ones on the fetch-bound core, and
; 3-operand (untied) unary/immediate ops (ISA v2: rd and rs1 independent).

define i64 @zext8(i64 %a) {
; CHECK-LABEL: zext8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    zextb r12, r0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %r = and i64 %a, 255
  ret i64 %r
}

define i64 @zext16(i64 %a) {
; CHECK-LABEL: zext16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    zexth r12, r0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %r = and i64 %a, 65535
  ret i64 %r
}

define i64 @bit_set3(i64 %a) {
; CHECK-LABEL: bit_set3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    bset r12, r0, 3
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %r = or i64 %a, 8
  ret i64 %r
}

define i64 @bit_set63(i64 %a) {
; CHECK-LABEL: bit_set63:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    bset r12, r0, 63
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %r = or i64 %a, -9223372036854775808
  ret i64 %r
}

define i64 @bit_clear40(i64 %a) {
; CHECK-LABEL: bit_clear40:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    bclr r12, r0, 40
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %r = and i64 %a, -1099511627777
  ret i64 %r
}

define i64 @bit_toggle32(i64 %a) {
; CHECK-LABEL: bit_toggle32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    btgl r12, r0, 32
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %r = xor i64 %a, 4294967296
  ret i64 %r
}

define i64 @load_idx(ptr %p, i64 %i) {
; CHECK-LABEL: load_idx:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    shlv r12, r1, 3
; CHECK-NEXT:    ldidx64r r12, r0, r12
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %a = getelementptr i64, ptr %p, i64 %i
  %v = load i64, ptr %a
  ret i64 %v
}

define void @store_idx(ptr %p, i64 %i, i64 %v) {
; CHECK-LABEL: store_idx:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    shlv r12, r1, 3
; CHECK-NEXT:    stidx64r r2, r0, r12
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %a = getelementptr i64, ptr %p, i64 %i
  store i64 %v, ptr %a
  ret void
}

; Source stays live: untied INCR/SHLV write a different register, no COPY.
define i64 @untied(i64 %a) {
; CHECK-LABEL: untied:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    incr r12, r0
; CHECK-NEXT:    mulr r12, r0, r12
; CHECK-NEXT:    shlv r12, r12, 4
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %b = add i64 %a, 1
  %c = shl i64 %a, 4
  %r = mul i64 %b, %c
  ret i64 %r
}

; setcc produces exactly 0/1 (ZeroOrOneBooleanContent): no masking ANDV.
define i64 @bool_zext(i64 %a, i64 %b) {
; CHECK-LABEL: bool_zext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    cmpultr r12, r0, r1
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %c = icmp ult i64 %a, %b
  %r = zext i1 %c to i64
  ret i64 %r
}
