; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=klausscpu -O1 < %s | FileCheck %s

; Loads and stores of all widths; zero-extend, sign-extend, truncate.

define i64 @load_i8_zext(ptr %p) {
; CHECK-LABEL: load_i8_zext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    memget8 r12, r0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %v = load i8, ptr %p
  %r = zext i8 %v to i64
  ret i64 %r
}

define i64 @load_i8_sext(ptr %p) {
; CHECK-LABEL: load_i8_sext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    ldidx8s r12, r0, 0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %v = load i8, ptr %p
  %r = sext i8 %v to i64
  ret i64 %r
}

define i64 @load_i16_zext(ptr %p) {
; CHECK-LABEL: load_i16_zext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    memget16 r12, r0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %v = load i16, ptr %p
  %r = zext i16 %v to i64
  ret i64 %r
}

define i64 @load_i16_sext(ptr %p) {
; CHECK-LABEL: load_i16_sext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    ldidx16s r12, r0, 0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %v = load i16, ptr %p
  %r = sext i16 %v to i64
  ret i64 %r
}

define i64 @load_i32_zext(ptr %p) {
; CHECK-LABEL: load_i32_zext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    memget32 r12, r0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %v = load i32, ptr %p
  %r = zext i32 %v to i64
  ret i64 %r
}

define i64 @load_i32_sext(ptr %p) {
; CHECK-LABEL: load_i32_sext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    memget32 r12, r0
; CHECK-NEXT:    sextw r12
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %v = load i32, ptr %p
  %r = sext i32 %v to i64
  ret i64 %r
}

define i64 @load_i64(ptr %p) {
; CHECK-LABEL: load_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    ldidx64 r12, r0, 0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %r = load i64, ptr %p
  ret i64 %r
}

define void @store_i8(ptr %p, i64 %v) {
; CHECK-LABEL: store_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    memset8 r1, r0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %t = trunc i64 %v to i8
  store i8 %t, ptr %p
  ret void
}

define void @store_i16(ptr %p, i64 %v) {
; CHECK-LABEL: store_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    memset16 r1, r0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %t = trunc i64 %v to i16
  store i16 %t, ptr %p
  ret void
}

define void @store_i32(ptr %p, i64 %v) {
; CHECK-LABEL: store_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    memset32 r1, r0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %t = trunc i64 %v to i32
  store i32 %t, ptr %p
  ret void
}

define void @store_i64(ptr %p, i64 %v) {
; CHECK-LABEL: store_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    stidx64 r1, r0, 0
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  store i64 %v, ptr %p
  ret void
}

; Indexed load: base + constant offset (tests LDIDX patterns).
define i64 @load_i64_offset(ptr %p) {
; CHECK-LABEL: load_i64_offset:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    ldidx64 r12, r0, 24
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %q = getelementptr i64, ptr %p, i64 3
  %r = load i64, ptr %q
  ret i64 %r
}

define void @store_i64_offset(ptr %p, i64 %v) {
; CHECK-LABEL: store_i64_offset:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    stidx64 r1, r0, 24
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %q = getelementptr i64, ptr %p, i64 3
  store i64 %v, ptr %q
  ret void
}
