; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --default-march klausscpu
; RUN: llc -march=klausscpu -O1 < %s | FileCheck %s

; SELECT expansion: no hardware CMOV — lowered to branch diamond + PHI.
; Each select becomes: CMPRV/CMPRR + JMPE + PHI.

define i64 @select_eq(i64 %cond, i64 %t, i64 %f) {
; CHECK-LABEL: select_eq:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    setr r12, 0
; CHECK-NEXT:    cmpeqr r12, r0, r12
; CHECK-NEXT:    cmprv r12, 0
; CHECK-NEXT:    jmpe .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    copy r2, r1
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    copy r12, r2
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %c = icmp eq i64 %cond, 0
  %r = select i1 %c, i64 %t, i64 %f
  ret i64 %r
}

define i64 @select_ne(i64 %cond, i64 %t, i64 %f) {
; CHECK-LABEL: select_ne:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    setr r12, 0
; CHECK-NEXT:    cmpner r12, r0, r12
; CHECK-NEXT:    cmprv r12, 0
; CHECK-NEXT:    jmpe .LBB1_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    copy r2, r1
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    copy r12, r2
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %c = icmp ne i64 %cond, 0
  %r = select i1 %c, i64 %t, i64 %f
  ret i64 %r
}

define i64 @select_slt(i64 %a, i64 %b, i64 %t, i64 %f) {
; CHECK-LABEL: select_slt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    cmpltr r12, r0, r1
; CHECK-NEXT:    cmprv r12, 0
; CHECK-NEXT:    jmpe .LBB2_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    copy r3, r2
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    copy r12, r3
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %c = icmp slt i64 %a, %b
  %r = select i1 %c, i64 %t, i64 %f
  ret i64 %r
}

; select with constant operands.
define i64 @select_const(i64 %cond) {
; CHECK-LABEL: select_const:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    setr r12, 0
; CHECK-NEXT:    cmpgtr r12, r0, r12
; CHECK-NEXT:    cmprv r12, 0
; CHECK-NEXT:    jmpe .LBB3_1
; CHECK-NEXT:    jmp .LBB3_2
; CHECK-NEXT:  .LBB3_1:
; CHECK-NEXT:    setr r12, 200
; CHECK-NEXT:    jmp .LBB3_3
; CHECK-NEXT:  .LBB3_2:
; CHECK-NEXT:    setr r12, 100
; CHECK-NEXT:  .LBB3_3:
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %c = icmp sgt i64 %cond, 0
  %r = select i1 %c, i64 100, i64 200
  ret i64 %r
}

; Chained selects.
define i64 @clamp(i64 %x, i64 %lo, i64 %hi) {
; CHECK-LABEL: clamp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    maxr r12, r0, r1
; CHECK-NEXT:    minr r12, r12, r2
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %c1 = icmp slt i64 %x, %lo
  %v1 = select i1 %c1, i64 %lo, i64 %x
  %c2 = icmp sgt i64 %v1, %hi
  %r  = select i1 %c2, i64 %hi, i64 %v1
  ret i64 %r
}
