; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=klausscpu -O1 < %s | FileCheck %s

; Varargs: va_start stores the address of the first vararg slot; va_arg advances
; a void* through the save area (R1-R3 slots) and then into caller stack args.
; With VoidPtrBuiltinVaList, va_start/va_end lower to a pointer store/no-op.

; Single named arg — first vararg is in R1 slot [incoming_SP+8].
define i64 @sum2(i64 %fmt, ...) {
; CHECK-LABEL: sum2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addsp -8
; CHECK-NEXT:    stidx64 r3, r15, 32
; CHECK-NEXT:    stidx64 r2, r15, 24
; CHECK-NEXT:    addr r12, r1, r2
; CHECK-NEXT:    addi r14, r15, 16
; CHECK-NEXT:    stidx64 r1, r15, 16
; CHECK-NEXT:    stidx64 r14, r15, -8
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %ap = alloca ptr
  call void @llvm.va_start.p0(ptr %ap)
  %p  = load ptr, ptr %ap
  %a  = load i64, ptr %p
  %p1 = getelementptr i64, ptr %p, i64 1
  %b  = load i64, ptr %p1
  %r  = add i64 %a, %b
  call void @llvm.va_end.p0(ptr %ap)
  ret i64 %r
}

; Two named args — first vararg is in R2 slot [incoming_SP+16].
define i64 @sum1_named2(i64 %a, i64 %b, ...) {
; CHECK-LABEL: sum1_named2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addsp -8
; CHECK-NEXT:    stidx64 r3, r15, 32
; CHECK-NEXT:    addr r12, r1, r2
; CHECK-NEXT:    addi r14, r15, 24
; CHECK-NEXT:    stidx64 r2, r15, 24
; CHECK-NEXT:    stidx64 r14, r15, -8
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %ap = alloca ptr
  call void @llvm.va_start.p0(ptr %ap)
  %p  = load ptr, ptr %ap
  %c  = load i64, ptr %p
  %r  = add i64 %b, %c
  call void @llvm.va_end.p0(ptr %ap)
  ret i64 %r
}

; All four regs named — first vararg is on stack at [incoming_SP+32].
define i64 @first_stack_vararg(i64 %a, i64 %b, i64 %c, i64 %d, ...) {
; CHECK-LABEL: first_stack_vararg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    push r15
; CHECK-NEXT:    getsp r15
; CHECK-NEXT:    addsp -8
; CHECK-NEXT:    addi r12, r15, 40
; CHECK-NEXT:    stidx64 r12, r15, -8
; CHECK-NEXT:    ldidx64 r12, r15, 40
; CHECK-NEXT:    addr r12, r3, r12
; CHECK-NEXT:    setsp r15
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    ret
  %ap = alloca ptr
  call void @llvm.va_start.p0(ptr %ap)
  %p  = load ptr, ptr %ap
  %e  = load i64, ptr %p
  %r  = add i64 %d, %e
  call void @llvm.va_end.p0(ptr %ap)
  ret i64 %r
}

; Sub-i64 va_arg must read the FULL 8-byte slot (ldidx64) and truncate, never a
; narrowed 32-bit MEMGET32.  The DAG combiner would otherwise reduce
; (trunc (ldidx64 slot)) to a register-addressed MEMGET32, which reads the wrong
; slot for va_arg's computed pointer on hardware (mixed-width printf "%u"
; garbles).  shouldReduceLoadWidth() returns false to prevent this.
define i64 @pick_u32(i64 %n, ...) {
; CHECK-LABEL: pick_u32:
; CHECK-NOT:     memget32
; CHECK:         ldidx64
; CHECK-NOT:     memget32
  %ap = alloca ptr
  call void @llvm.va_start.p0(ptr %ap)
  %a = va_arg ptr %ap, i32
  %b = va_arg ptr %ap, i32
  %c = va_arg ptr %ap, i32
  call void @llvm.va_end.p0(ptr %ap)
  %za = zext i32 %a to i64
  %zb = zext i32 %b to i64
  %zc = zext i32 %c to i64
  %s1 = add i64 %za, %zb
  %s2 = add i64 %s1, %zc
  ret i64 %s2
}

declare void @llvm.va_start.p0(ptr)
declare void @llvm.va_end.p0(ptr)
